// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/VOTONO/go-metrics/internal/server/repo (interfaces: MetricStorer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/VOTONO/go-metrics/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMetricStorer is a mock of MetricStorer interface.
type MockMetricStorer struct {
	ctrl     *gomock.Controller
	recorder *MockMetricStorerMockRecorder
}

// MockMetricStorerMockRecorder is the mock recorder for MockMetricStorer.
type MockMetricStorerMockRecorder struct {
	mock *MockMetricStorer
}

// NewMockMetricStorer creates a new mock instance.
func NewMockMetricStorer(ctrl *gomock.Controller) *MockMetricStorer {
	mock := &MockMetricStorer{ctrl: ctrl}
	mock.recorder = &MockMetricStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricStorer) EXPECT() *MockMetricStorerMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockMetricStorer) All(arg0 context.Context) (map[string]models.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0)
	ret0, _ := ret[0].(map[string]models.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockMetricStorerMockRecorder) All(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockMetricStorer)(nil).All), arg0)
}

// Get mocks base method.
func (m *MockMetricStorer) Get(arg0 context.Context, arg1 string) (models.Metric, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(models.Metric)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricStorerMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricStorer)(nil).Get), arg0, arg1)
}

// StoreSingle mocks base method.
func (m *MockMetricStorer) StoreSingle(arg0 context.Context, arg1 models.Metric) (*models.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSingle", arg0, arg1)
	ret0, _ := ret[0].(*models.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreSingle indicates an expected call of StoreSingle.
func (mr *MockMetricStorerMockRecorder) StoreSingle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSingle", reflect.TypeOf((*MockMetricStorer)(nil).StoreSingle), arg0, arg1)
}

// StoreSlice mocks base method.
func (m *MockMetricStorer) StoreSlice(arg0 context.Context, arg1 []models.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSlice", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSlice indicates an expected call of StoreSlice.
func (mr *MockMetricStorerMockRecorder) StoreSlice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSlice", reflect.TypeOf((*MockMetricStorer)(nil).StoreSlice), arg0, arg1)
}
